version: "3.9"

services:
  app:
    build: .
    container_name: ci4_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./docker/app/entrypoint.sh:/usr/local/bin/ci-boot.sh:ro
    environment:
      DB_HOST: db
      DB_NAME: todo
      DB_USER: app
      DB_PASS: app
      APP_ENV: development
      COMPOSER_ALLOW_SUPERUSER: "1"
      MIGRATE_ON_BOOT: "1"
    entrypoint: ["/bin/sh","-lc","ci-boot.sh && php-fpm"]
    depends_on:
      db:
        condition: service_healthy

  web:
    image: nginx:1.27-alpine
    container_name: ci4_web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html:rw
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mariadb:11
    container_name: ci4_db
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  db_data:
